BlogSite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from blog import views

app_name = 'blog'

urlpatterns = [
    path('', views.home, name='home'),
    path('blog/', views.blog, name='blog'),
    # path('', views.BlogListView.as_view(), name='blog'),
    path('post/<int:post_id>/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post, name='post'),
    path('send_email/<int:post_id>/', views.send_email, name='send_email'),
    path('comment/<int:post_id>/<int:year>/<int:month>/<int:day>/<slug:slug>/', views.post_comment, name='post_comment'),
    path('tag/<slug:tag_slug>/', views.post, name='post_by_tag'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from taggit.managers import TaggableManager


# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):

    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date='publish')
    intro_text = models.TextField(blank=True)
    body = models.TextField()
    post_image = models.ImageField(upload_to='images/', blank=True)
    created = models.DateTimeField(auto_now_add=True)
    publish = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT)
    objects = models.Manager()
    published = PublishedManager()
    tags = TaggableManager()

    class Meta:
        ordering = ["-publish"]
        indexes = [
            models.Index(fields=["-publish"]),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post',
                       args=[self.id,
                             self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug]
                       )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name='comments'
                             )
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created'])
        ]

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
from django import forms

from blog.models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']

blog/views.py
from django.core.mail import send_mail
from django.db.models import Count
from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from taggit.models import Tag

from blog.forms import EmailPostForm, CommentForm
from blog.models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.


def home(request):
    return render(request, "blog/index.html")


def blog(request, tag_slug=None):
    posts = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    # Pagination with three posts per page.
    paginator = Paginator(posts, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts_list = paginator.page(page_number)
    except PageNotAnInteger:
        # if page_number is not an integer the first page is viewed
        posts_list = paginator.page(1)
    except EmptyPage:
        # if page is out of range
        posts_list = paginator.page(paginator.num_pages)
    return render(request, "blog/blog.html", {'posts': posts_list, 'tag': tag})


# class BlogListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/blog.html'


def send_email(request, post_id):
    each_post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    sent = False

    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # form passed validation
            cd = form.cleaned_data
            # ....send email
            post_url = request.build_absolute_uri(
                each_post.get_absolute_url()
            )
            subject = f"{cd['name']} recommends you read " \
                      f"{each_post.title}"
            message = f"Read {each_post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'your_account@gmail.com',
                      [cd['to']])
            sent = True

    else:
        form = EmailPostForm()

    return render(request, 'blog/post.html', {'post': each_post, 'form': form, 'sent': sent})


def post(request,  post_id, year, month, day, slug):
    # retrieving the post
    each_post = get_object_or_404(Post,
                                  status=Post.Status.PUBLISHED,
                                  id=post_id,
                                  slug=slug,
                                  publish__year=year,
                                  publish__month=month,
                                  publish__day=day)

    # List of all active comments for this post
    comments = each_post.comments.filter(active=True)
    # Form for users to comment
    form = CommentForm()

    # List of similar posts
    post_tags_ids = each_post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=each_post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
    return render(request, "blog/post.html", {'post': each_post,
                                              'comments': comments,
                                              'form': form,
                                              'similar_posts': similar_posts,
                                              })


@require_POST
def post_comment(request,  post_id, year, month, day, slug):
    # each_post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)

    each_post = get_object_or_404(Post,
                                  status=Post.Status.PUBLISHED,
                                  id=post_id,
                                  slug=slug,
                                  publish__year=year,
                                  publish__month=month,
                                  publish__day=day)

    comment = None
    # A comment was posted
    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Create a comment object without saving it to the database
        comment = form.save(commit=False)
        # Assign the post to the comment
        comment.post = each_post
        # save the comment to the database
        comment.save()
        return redirect('blog:post', each_post.id, each_post.publish.year,
                        each_post.publish.month,
                        each_post.publish.day,
                        each_post.slug,
                        )

    return render(request, 'blog/post.html', {'post': each_post,
                                              'form': form,
                                              'comment': comment
                                              })

templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title> {% block title %}Bootstrap Blog - B5 Template by Bootstrap Temple {% endblock %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <!-- Google fonts - Open Sans-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <!-- gLightbox-->
    <link rel="stylesheet" href="{% static "blog/vendor/glightbox/css/glightbox.css" %}">
    <!-- Theme stylesheet-->
    <link rel="stylesheet" href="{% static "blog/css/style.default.css" %}" id="theme-stylesheet">
    <!-- gLightbox-->
    <link rel="stylesheet" href="{% static "blog/vendor/glightbox/css/glightbox.min.css" %}">
    <!-- Custom stylesheet - for your changes-->
    <link rel="stylesheet" href="{% static "blog/css/custom.css" %}">
    <!-- Favicon-->
    <link rel="shortcut icon" href="{% static "blog/img/favicon.ico" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white border-bottom py-3">
      <div class="container py-1"><a class="navbar-brand text-sm fw-bold text-dark" href="{% url 'blog:home' %}">Bootstrap Blog</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span></span><span></span><span></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0 align-items-lg-center">
            <li class="nav-item"><a class="nav-link " href="{% url 'blog:home' %}">Home</a>
            </li>
            <li class="nav-item"><a class="nav-link " href="{% url 'blog:blog' %}">Blog</a>
            </li>
            <li class="nav-item"><a class="nav-link active " href=" ">Post</a>
            </li>
            <li class="nav-item"><a class="nav-link " href="#">Contact</a>
            </li>
            <li class="nav-item mt-2 mt-lg-0">
              <ul class="list-inline d-flex align-items-center">
                <li class="list-inline-item mx-lg-2 px-2 border-start border-end"><a class="search-btn nav-link small py-0 text-dark" href="#"><i class="fas fa-search"></i></a></li>
                <li class="list-inline-item d-flex align-items-end small"><a class="text-dark" href="#">EN</a><span class="underscore mb-1"></span><a class="text-gray-500" href="#">ES</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="search-area">
      <div class="search-area-inner d-flex align-items-center justify-content-center position-relative">
        <div class="close-btn position-absolute p-4 top-0 end-0 cursor-pointer z-index-20"><i class="fas fa-times"></i></div>
        <div class="row d-flex justify-content-center w-100">
          <div class="col-md-8">
            <form action="#">
              <div class="input-group border-bottom">
                <input class="form-control form-control-lg border-0 shadow-0 ps-0 bg-none px-0" type="search" placeholder="What are you looking for?">
                <button class="btn btn-link btn-sm shadow-0 px-0 btn-lg text-dark" type="submit"><i class="fas fa-search"></i></button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>

    
{% block body %}
        
{% endblock %}
    
    <!-- Page Footer-->
    <footer class="footer text-white" style="background: #0e0e0e">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <h6 class="text-white">Bootstrap Blog</h6>
            <p class="fw-light mb-1">53 Broadway, Broklyn, NY 11249</p>
            <p class="fw-light mb-1">Phone: (020) 123 456 789</p>
            <p class="fw-light mb-4">Email: <a class="text-decoration-underline text-reset" href="mailto:info@company.com">Info@Company.com</a></p>
            <ul class="list-unstyled">
              <li class="list-inline-item"><a class="text-reset me-2" href="!#"><i class="fab fa-facebook-f"></i></a></li>
              <li class="list-inline-item"><a class="text-reset me-2" href="!#"><i class="fab fa-twitter"></i></a></li>
              <li class="list-inline-item"><a class="text-reset me-2" href="!#"><i class="fab fa-instagram"></i></a></li>
              <li class="list-inline-item"><a class="text-reset me-2" href="!#"><i class="fab fa-behance"></i></a></li>
              <li class="list-inline-item"><a class="text-reset me-2" href="!#"><i class="fab fa-pinterest"></i></a></li>
            </ul>
          </div>
          <div class="col-md-4">
            <div class="d-flex">
              <ul class="list-unstyled text-sm me-4">
                <li class="mb-2"><a class="text-reset fw-light" href="!#">My Account</a></li>
                <li class="mb-2"><a class="text-reset fw-light" href="!#">Add Listing</a></li>
                <li class="mb-2"><a class="text-reset fw-light" href="!#">Pricing</a></li>
                <li class="mb-2"><a class="text-reset fw-light" href="!#">Privacy &amp; Policy</a></li>
              </ul>
              <ul class="list-unstyled text-sm">
                <li class="mb-2"><a class="text-reset fw-light" href="!#">Our Partners</a></li>
                <li class="mb-2"><a class="text-reset fw-light" href="!#">FAQ</a></li>
                <li class="mb-2"><a class="text-reset fw-light" href="!#">How It Works</a></li>
                <li class="mb-2"><a class="text-reset fw-light" href="!#">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4"><a class="d-block mb-2" href=" ">
              <div class="d-flex align-items-center"><img class="img-fluid p-1 border border-gray-600 flex-shrink-0" src="{% static "blog/img/small-thumbnail-1.jpg" %}" alt="..." width="50">
                <div class="ms-2 text-muted">
                  <p class="fw-bold mb-0">Hotels for all budgets</p><span>October 26, 2016</span>
                </div>
              </div></a><a class="d-block mb-2" href=" ">
              <div class="d-flex align-items-center"><img class="img-fluid p-1 border border-gray-600 flex-shrink-0" src="{% static "blog/img/small-thumbnail-2.jpg" %}" alt="..." width="50">
                <div class="ms-2 text-muted">
                  <p class="fw-bold mb-0">Great street atrs in London</p><span>October 26, 2016</span>
                </div>
              </div></a><a class="d-block" href=" ">
              <div class="d-flex align-items-center"><img class="img-fluid p-1 border border-gray-600 flex-shrink-0" src="{% static "blog/img/small-thumbnail-3.jpg" %}" alt="..." width="50">
                <div class="ms-2 text-muted">
                  <p class="fw-bold mb-0">Best coffee shops in Sydney</p><span>October 26, 2016</span>
                </div>
              </div></a>
          </div>
        </div>
      </div>
    </footer>
    <div class="copyrights text-white py-4" style="background: #090909">
      <div class="container">
        <div class="row text-center gy-2">
          <div class="col-md-6 text-md-start">
            <p class="mb-0 fw-light text-sm">&copy; 2022. All rights reserved. Your great site.</p>
          </div>
          <div class="col-md-6 text-md-end">
            <p class="mb-0 text-sm">Template By <a class="text-reset fw-light" href="https://bootstrapious.com/p/bootstrap-blog">Bootstrapious</a>
              <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
            </p>
          </div>
        </div>
      </div>
    </div>
    <!-- JavaScript files-->
    <script src="{% static "blog/vendor/bootstrap/js/bootstrap.bundle.min.js" %}"></script>
    <script src="{% static "blog/vendor/glightbox/js/glightbox.min.js" %}"></script>
    <script src="{% static "blog/js/theme.js" %}"></script>
    <!-- FontAwesome CSS - loading as last, so it doesn't block rendering-->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
  </body>
</html>

templates/blog/post.html
{% extends "blog/base.html" %}
{% load static %}

{% block title %} {% endblock %}

{% block body %}
    <section class="py-5">
      <div class="container">
        <div class="row gy-5">
          <!-- Latest Posts -->
          <main class="col-lg-8"> 
            <div class="container"><img class="img-fluid w-100 mb-4" src="{{post.post_image.url}}" alt="...">
              <ul class="list-inline mb-3">
                <li class="list-inline-item"><a class="text-uppercase" href="!#">Business</a></li>
                <li class="list-inline-item"><a class="text-uppercase" href="!#">Technology</a></li>
              </ul>
              <h1 class="mb-4">{{ post.title }}<a href="!#"><i class="fa fa-bookmark-o"></i></a></h1>
              <ul class="list-inline list-separated text-gray-500 mb-5">
                <li class="list-inline-item"><a class="d-flex align-items-center flex-wrap text-reset" href="!#">
                    <div class="avatar flex-shrink-0"><img class="img-fluid" src="{% static "blog/img/avatar-1.jpg" %}" alt="..."></div><small>{{ post.author }}</small></a></li>
                <li class="list-inline-item small"><i class="far fa-clock"></i> {{ post.updated }} </li>
                <li class="list-inline-item small"><i class="far fa-comment"></i> 12</li>
              </ul>
              <div class="post-body">
                <p class="lead">{{ post.intro_text }}</p>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
                <p class="mb-4"><img class="img-fluid" src="{% static "blog/img/featured-pic-3.jpeg" %}" alt="..."></p>
                <h3>Lorem Ipsum Dolor</h3>
                <p class="mb-4">{{ post.body }}</p>
                <div class="border-start border-4 mb-3">
                  <figure class="border p-4">
                    <blockquote class="blockquote">
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut
                              labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                              laboris nisi ut aliquip.</p>
                    </blockquote>
                    <figcaption class="blockquote-footer mb-0">Someone famous in
                      <cite title="Source Title">Source Title</cite>
                    </figcaption>
                  </figure>
                </div>
                <p>{{ post.body }}</p>
              </div>
            {% if tag %}
              <ul class="list-inline mb-5">
              <h3> Posts tagged with </h3>
                <li class="list-inline-item"><a class="tag" href="!#">#{{ tag.name }}</a></li>
                <li class="list-inline-item"><a class="tag" href="!#">#Tricks</a></li>
                <li class="list-inline-item"><a class="tag" href="!#">#Financial</a></li>
                <li class="list-inline-item"><a class="tag" href="!#">#Economy</a></li>
              </ul>
            {% endif %}

            {% for tag in post.tags.all %}
            <a href="{% url "blog:post_by_tag" tag.slug %}">
            {{ tag.name }}
            </a>
            {% if not forloop.last %}, {% endif %}
            {% endfor %}



              <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row mb-5"><a class="prev-post text-start d-flex align-items-center" href="!#">
                  <div class="icon prev"><i class="fas fa-angle-left"></i></div>
                  <div class="text"><strong class="text-primary">Previous Post </strong>
                    <h6>I Bought a Wedding Dress.</h6>
                  </div></a><a class="next-post text-end d-flex align-items-center justify-content-end" href="!#">
                  <div class="text"><strong class="text-primary">Next Post </strong>
                    <h6>I Bought a Wedding Dress.</h6>
                  </div>
                  <div class="icon next"><i class="fas fa-angle-right">   </i></div></a></div>

              <div class="mb-5">
                  {% with comments.count as total_comments %}
                <header>
                  <h3 class="h6 mb-4">Post Comments<span class="fw-light text-gray-600 small ms-2">({{ total_comments }})</span></h3>
                </header>
                {% endwith %}

              {% for comment in comments %}
                  {% if comments %}
                <div class="d-flex align-items-start"><img class="img-fluid rounded-circle flex-shrink-0" src="{% static "blog/img/user.svg" %}" alt="Jabi Hernandiz" width="50"/>
                  <div class="pb-4 ms-3 border-bottom mb-4"><strong>{{ comment.name }}</strong>
                    <p class="small text-gray-500">{{ comment.created }}</p>
                    <p class="mb-0 text-sm">{{ comment.body}}</p>
                      {% else %}
                      <p> There are no comments. </p>
                      {% endif %}
                  </div>
                </div>
              {% endfor %}


{#              <div class="mb-5">#}
{#                <header>#}
{#                  <h3 class="h6 mb-4">Leave a reply</h3>#}
{#                </header>#}
{#                <form action="#">#}
{#                  <div class="row gy-3">#}
{#                    <div class="col-md-6">#}
{#                      <div class="border-bottom">#}
{#                        <input class="form-control px-0 border-0 shadow-0" type="text" name="username" id="username" placeholder="Name">#}
{#                      </div>#}
{#                    </div>#}
{#                    <div class="col-md-6">#}
{#                      <div class="border-bottom">#}
{#                        <input class="form-control px-0 border-0 shadow-0" type="email" name="username" id="useremail" placeholder="Email Address (will not be published)">#}
{#                      </div>#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                      <div class="border-bottom">#}
{#                        <textarea class="form-control px-0 border-0 shadow-0" rows="5" name="usercomment" id="usercomment" placeholder="Type your comment"></textarea>#}
{#                      </div>#}
{#                    </div>#}
{#                    <div class="col-md-12">#}
{#                      <button class="btn btn-secondary" type="submit">Submit Comment</button>#}
{#                    </div>#}
{#                  </div>#}
{#                </form>#}
{#              </div>#}
{#            </div>#}

{#              Adding comments #}
            {% if comment %}
            <h2>Your comment has been added.</h2>
            <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
            {% else %}
                <h2>Add a new comment</h2>
                <form action="{% url "blog:post_comment" post.id post.publish.year post.publish.month post.publish.day post.slug %}" method="post">
                {{ form.as_p }}
                {% csrf_token %}
                <p><input type="submit" value="Add comment"></p>
                </form>
            {% endif %}


           <div class="mb-5">
               {% if sent %}
                <h1>E-mail successfully sent</h1>
                <p>
                "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
                </p>
               {% else %}
                    <h1>Share "{{ post.title }}" by e-mail</h1>
                    <form method="post">
                    {{ form.as_p }}
                    {% csrf_token %}
                    <input type="submit" value="Send e-mail">
                    </form>
                    {% endif %}
              </div>
            

                <h2>Similar posts</h2>
                {% for post in similar_posts %}
                <p>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </p>
                {% empty %}
                There are no similar posts yet.
                {% endfor %}


          </main>
          <aside class="col-lg-4">
            <!-- Widget [Search Bar Widget]-->
            <div class="card mb-5">
              <div class="card-body">
                <h3 class="h6">Search the blog</h3>
                <form action="#">
                  <div class="input-group border-bottom">
                    <input class="form-control border-0 shadow-0 ps-0" type="search" placeholder="What are you looking for?">
                    <button class="btn btn-link btn-sm shadow-0 px-0" type="submit"><i class="fas fa-search"></i></button>
                  </div>
                </form>
              </div>
            </div>
            <!-- Widget [Latest Posts Widget]        -->
            <div class="card mb-5">
              <div class="card-body">
                <h3 class="h6 mb-3">Latest Posts</h3><a class="text-reset mb-3" href="!#">
                  <div class="d-flex align-items-center"><img class="img-fluid flex-shrink-0" src="{% static "blog/img/small-thumbnail-1.jpg" %}" alt="..." width="55">
                    <div class="ms-3">
                      <p class="mb-2 fw-bold text-gray-700 lh-1">Alberto Savoia Can Teach You About</p>
                      <ul class="list-inline list-separated text-gray-500 d-flex align-items-center">
                        <li class="list-inline-item small"><i class="far fa-eye"></i> 500</li>
                        <li class="list-inline-item small"><i class="far fa-comment"></i> 12</li>
                      </ul>
                    </div>
                  </div></a><a class="text-reset mb-3" href="!#">
                  <div class="d-flex align-items-center"><img class="img-fluid flex-shrink-0" src="{% static "blog/img/small-thumbnail-2.jpg" %}" alt="..." width="55">
                    <div class="ms-3">
                      <p class="mb-2 fw-bold text-gray-700 lh-1">Alberto Savoia Can Teach You About</p>
                      <ul class="list-inline list-separated text-gray-500 d-flex align-items-center">
                        <li class="list-inline-item small"><i class="far fa-eye"></i> 500</li>
                        <li class="list-inline-item small"><i class="far fa-comment"></i> 12</li>
                      </ul>
                    </div>
                  </div></a><a class="text-reset" href="!#">
                  <div class="d-flex align-items-center"><img class="img-fluid flex-shrink-0" src="{% static "blog/img/small-thumbnail-3.jpg" %}" alt="..." width="55">
                    <div class="ms-3">
                      <p class="mb-2 fw-bold text-gray-700 lh-1">Alberto Savoia Can Teach You About</p>
                      <ul class="list-inline list-separated text-gray-500 d-flex align-items-center">
                        <li class="list-inline-item small"><i class="far fa-eye"></i> 500</li>
                        <li class="list-inline-item small"><i class="far fa-comment"></i> 12</li>
                      </ul>
                    </div>
                  </div></a>
              </div>
            </div>
            <!-- Widget [Categories Widget]-->
            <div class="card mb-5">
              <div class="card-body">
                <h3 class="h6 mb-3">Categories</h3>
                <div class="p-2 d-flex justify-content-between fw-bold text-gray-600 bg-light"><a class="text-reset" href="!#">Growth</a><span>12</span></div>
                <div class="p-2 d-flex justify-content-between fw-bold text-gray-600 1"><a class="text-reset" href="!#">Local</a><span>25</span></div>
                <div class="p-2 d-flex justify-content-between fw-bold text-gray-600 bg-light"><a class="text-reset" href="!#">Sales</a><span>8</span></div>
                <div class="p-2 d-flex justify-content-between fw-bold text-gray-600 1"><a class="text-reset" href="!#">Tips</a><span>17</span></div>
                <div class="p-2 d-flex justify-content-between fw-bold text-gray-600 bg-light"><a class="text-reset" href="!#">Local</a><span>25</span></div>
              </div>
            </div>


            <!-- Widget [Tags Cloud Widget]-->
            <div class="card">
              <div class="card-body">     
                <h3 class="h6 mb-3">Tags</h3>
                <ul class="list-inline mb-0">
                    {% for tag in post.tags.all %}
                  <li class="list-inline-item"><a class="tag" href="!#">#{{ tag }}</a></li>
                    {% endfor %}
                  <li class="list-inline-item"><a class="tag" href="!#">#Fashion </a></li>
                  <li class="list-inline-item"><a class="tag" href="!#">#Sports </a></li>
                  <li class="list-inline-item"><a class="tag" href="!#">#Technology </a></li>
                  <li class="list-inline-item"><a class="tag" href="!#">#Economy </a></li>
                </ul>
              </div>
            </div>
          </aside>
        </div>
      </div>
    </section>

{% endblock %}